### ISSUE TITLE
Localization options 

### ISSUE THREAD

**Issue by chagevik** [Esri/map-carousel-template#3] opened 2016-05-04 14:15 UTC
Hello, I am working on a support issue with a Spanish user who is trying to deploy this app. However, it looks like the app is only available as localized for French (C:\inetpub\wwwroot\map-carousel-template-master\js\nls). Is it possible to provide localization for es (Spanish) for this application when deployed locally? Thanks!

**Comment by jgravois** [comment] 2016-05-04 14:32
have you tried deploying the `es` files below?
https://github.com/Esri/map-carousel-template/tree/master/nls/es

**Comment by cher7369** [comment] 2016-05-04 14:34
Thanks John! I am working on adding the file now. For some reason all of the nls files are not coming through on the download for me and the customer. I realized the file was there after adding the issue, so may have jumped the gun.

I appreciate your quick response!

Cheryl

**Comment by jgravois** [comment] 2016-05-04 16:45
i'm seeing proper file structure in the `Download ZIP` link in the project homepage.  if you're still experiencing errors and can provide additional information i'd be happy to dig in deeper.

**Comment by cher7369** [comment] 2016-05-05 12:25
Hi John,

It looks like I am not seeing the full download when using Chrome (50.0.2661.94). However, I was able to get all of the nls folders successfully when downloading through Firefox (46.0).

Thanks,
Cheryl

**Comment by jgravois** [comment] 2016-05-05 20:11
> I am not seeing the full download when using Chrome (50.0.2661.94)

strange.  im not having any trouble using Chrome `50.0.2661.86` on my mac.

**Comment by cher7369** [comment] 2016-05-06 13:06
That is odd!

**Comment by cher7369** [comment] 2016-05-06 14:35
Hi John,

We are also seeing this issue with the Hosted Map Carousel app when any browser is set to Spanish language settings. The app is unable to access the map-carousel-template-master\map-carousel-template-master\nls\es folder. I am not sure if you also handle issues with the Hosted Configurable App? I am also going to submit a support defect, but wanted to go ahead and pass along the details.

Here are the browser versions where I have reproduced the issue:
Chrome 50.0.2661.94 m, Firefox 46.0.1, IE 11
I suspect the issue will also occur with browser language settings other than French and English but have not tested yet. Please let me know if there is anything else I can do to help with this issue.

Thanks!

Cheryl

**Comment by iwittenmyer** [comment] 2016-05-06 16:15
Hi, we have a bug for this that is scheduled to be fixed in the June release of arcgis online. 

BUG-000096260 Map Carousel application template will not load when browser language is set to German.  Every locale but Fr and En are involved.

**Comment by cher7369** [comment] 2016-05-06 16:18
Great thanks Ian! Glad to hear that the issue is being addressed and that I can attach to the existing defect.

Cheryl

**Closed as completed** 2017-03-29 23:27 UTC
